services:
  - type: web
    name: workout-ml-api
    env: python
    region: singapore
    rootDir: ml
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
